language: node_js
node_js:
  - "5"
before_script:
  - npm install -g codecov nyc
script:
  - nyc npm test
after_success:
  - nyc report --reporter=lcov
  - codecov --token=93108552-0ff8-49a6-ac00-5f308815f1e3
